name: Auto Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.13

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          echo "GITHUB_PAGES=false" >> $GITHUB_ENV

      - name: Build
        run: npm ci && npm run build

      - name: Deploy to S3
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-1
          aws s3 sync dist/ s3://ar-app-bucket-prog/